//Los types sirven para ir viendo que esta pasando en tu aplicacion
//Los TYPES se importan en proyectoState
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_SELECCIONADO = 'PROYECTO_SELECCIONADO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const AGREGAR_TAREA_P = 'AGREGAR_TAREA_P';
export const VALIDAR_TAREA_P = 'VALIDAR_TAREA_P';
export const ELIMINAR_TAREA_P = 'ELIMINAR_TAREA_P';
export const ESTADO_TAREA_P = 'ESTADO_TAREA_P';
export const TAREA_SELECCIONADA = 'TAREA_SELECCIONADA';
export const ACTUALIZAR_TAREA_P = 'ACTUALIZAR_TAREA_P';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
